export const POST_GET_ALL_POST = 'POST_GET_ALL_POST';
export const POST_GET_ALL_POST_DONE = 'POST_GET_ALL_POST_DONE';
export const POST_CREATE_NEW_POST = 'POST_CREATE_NEW_POST';

export const POST_COMMENT_GET_POST_COMMENT = 'POST_COMMENT_GET_POST_COMMENT';
export const POST_COMMENT_GET_POST_COMMENT_DONE =
  'POST_COMMENT_GET_POST_COMMENT_DONE';
export const POST_COMMENT_CREATE_POST_COMMENT =
  'POST_COMMENT_CREATE_POST_COMMENT';
