export const SOCKET_CLIENT_SEND_PROFILE = 'SOCKET_CLIENT_SEND_PROFILE';

export const SOCKET_CLIENT_SEND_NEW_POST = 'SOCKET_CLIENT_SEND_NEW_POST';
export const SOCKET_SERVER_SEND_NEW_POST = 'SOCKET_SERVER_SEND_NEW_POST';
