export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';

export const ACCOUNT_HAS_EMAIL = 'ACCOUNT_HAS_EMAIL';
export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const ACCOUNT_UPDATE_AVATAR = 'ACCOUNT_UPDATE_AVATAR';
export const ACCOUNT_UPDATE_AVATAR_SUCCESS = 'ACCOUNT_UPDATE_AVATAR_SUCCESS';

export const ACCOUNT_UPDATE_INFO = 'ACCOUNT_UPDATE_INFO';
export const ACCOUNT_UPDATE_INFO_SUCCESS = 'ACCOUNT_UPDATE_INFO_SUCCESS';
