export const USER_QUESTION_GETLIST_INFO_EXAM =
  'USER_QUESTION_GETLIST_INFO_EXAM';
export const USER_QUESTION_GETLIST_INFO_EXAM_DONE =
  'USER_QUESTION_GETLIST_INFO_EXAM_DONE';

export const USER_QUESTION_GETLIST_RATE_USER =
  'USER_QUESTION_GETLIST_RATE_USER';
export const USER_QUESTION_GETLIST_RATE_USER_DONE =
  'USER_QUESTION_GETLIST_RATE_USER_DONE';

export const USER_QUESTION_GETLIST_PERCENT_TOPIC =
  'USER_QUESTION_GETLIST_PERCENT_TOPIC';
export const USER_QUESTION_GETLIST_PERCENT_TOPIC_DONE =
  'USER_QUESTION_GETLIST_PERCENT_TOPIC_DONE';

export const USER_QUESTION_CREATE = 'USER_QUESTION_CREATE';
export const USER_QUESTION_UPDATE = 'USER_QUESTION_UPDATE';
